export const PRODUCTS = [
  {
    id: 'arl',
    name: 'ARL',
    fullName: 'Administradora de Riesgos Laborales',
    tagline: 'Protección en cada jornada',
    description: 'Cobertura integral para accidentes de trabajo y enfermedades laborales. Protege a tus empleados y cumple con la normativa colombiana vigente.',
    price: 'Desde $45.000/mes',
    color: 'from-blue-600 to-cyan-500',
    accentColor: '#3b82f6',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    icon: '🏗️',
    features: [
      'Accidentes de trabajo',
      'Enfermedades laborales',
      'Rehabilitación profesional',
      'Pensión por invalidez',
      'Muerte por accidente laboral',
      'Asistencia 24/7',
    ],
    badge: 'Obligatorio',
    badgeColor: 'bg-red-500',
  },
  {
    id: 'vida',
    name: 'Seguro de Vida',
    fullName: 'Seguro de Vida Individual',
    tagline: 'Cuida a quienes más amas',
    description: 'Asegura el futuro de tu familia con planes flexibles que se adaptan a tu presupuesto. Cobertura por muerte, invalidez total y enfermedades graves.',
    price: 'Desde $35.000/mes',
    color: 'from-purple-600 to-pink-500',
    accentColor: '#8b5cf6',
    image: 'https://images.unsplash.com/photo-1609220136736-443140cffec6?w=800&q=80',
    icon: '❤️',
    features: [
      'Indemnización por muerte',
      'Invalidez total permanente',
      'Enfermedades graves',
      'Auxilio funerario',
      'Rentas por incapacidad',
      'Beneficiarios múltiples',
    ],
    badge: 'Más vendido',
    badgeColor: 'bg-purple-500',
  },
  {
    id: 'salud',
    name: 'Seguro de Salud',
    fullName: 'Plan Complementario de Salud',
    tagline: 'Tu bienestar, nuestra misión',
    description: 'Accede a los mejores especialistas y clínicas sin largas esperas. Cobertura para hospitalización, cirugías, medicamentos y más.',
    price: 'Desde $120.000/mes',
    color: 'from-emerald-600 to-teal-500',
    accentColor: '#10b981',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    icon: '🏥',
    features: [
      'Hospitalizaciones',
      'Cirugías programadas',
      'Urgencias médicas',
      'Medicamentos cubiertos',
      'Consultas especializadas',
      'Exámenes diagnósticos',
    ],
    badge: 'Premium',
    badgeColor: 'bg-emerald-500',
  },
  {
    id: 'hogar',
    name: 'Seguro de Hogar',
    fullName: 'Protección para tu Hogar',
    tagline: 'Tu casa, siempre protegida',
    description: 'Protege tu propiedad y contenido contra incendios, robos, terremotos y desastres naturales. Tranquilidad para ti y tu familia.',
    price: 'Desde $55.000/mes',
    color: 'from-orange-500 to-amber-400',
    accentColor: '#f97316',
    image: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    icon: '🏡',
    features: [
      'Incendio y explosión',
      'Robo y hurto',
      'Terremotos',
      'Inundaciones',
      'Responsabilidad civil',
      'Daños eléctricos',
    ],
    badge: 'Nuevo',
    badgeColor: 'bg-orange-500',
  },
  {
    id: 'auto',
    name: 'SOAT',
    fullName: 'Seguro Obligatorio Automotor',
    tagline: 'Maneja con confianza',
    description: 'El SOAT es obligatorio para circular en Colombia. Cubre gastos médicos, incapacidad y muerte en accidentes de tránsito.',
    price: 'Desde $180.000/año',
    color: 'from-red-600 to-rose-500',
    accentColor: '#ef4444',
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80',
    icon: '🚗',
    features: [
      'Gastos médicos',
      'Incapacidad temporal',
      'Invalidez permanente',
      'Muerte',
      'Gastos funerarios',
      'Expedición inmediata',
    ],
    badge: 'Obligatorio',
    badgeColor: 'bg-red-500',
  },
  {
    id: 'empresarial',
    name: 'Seguro Empresarial',
    fullName: 'Cobertura Empresarial Integral',
    tagline: 'Protege tu negocio',
    description: 'Soluciones integrales para empresas de todos los tamaños. Protege activos, responsabilidad civil, empleados y continuidad del negocio.',
    price: 'Cotización personalizada',
    color: 'from-slate-600 to-blue-700',
    accentColor: '#64748b',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80',
    icon: '🏢',
    features: [
      'Activos físicos',
      'Responsabilidad civil',
      'Lucro cesante',
      'Manejo y fidelidad',
      'Transporte de valores',
      'Seguro colectivo',
    ],
    badge: 'Empresas',
    badgeColor: 'bg-slate-500',
  },
]

export const STATS = [
  { value: '50,000+', label: 'Clientes protegidos', icon: '👥' },
  { value: '98%', label: 'Satisfacción del cliente', icon: '⭐' },
  { value: '24/7', label: 'Atención continua', icon: '🕐' },
  { value: '15+', label: 'Años de experiencia', icon: '🏆' },
]

export const TEAM = [
  {
    name: 'María Fernanda López',
    role: 'CEO & Fundadora',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    bio: 'Más de 20 años en la industria aseguradora latinoamericana.',
  },
  {
    name: 'Carlos Andrés Ruiz',
    role: 'Director Comercial',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80',
    bio: 'Especialista en seguros corporativos y gestión de riesgos empresariales.',
  },
  {
    name: 'Laura Milena Torres',
    role: 'Directora de Siniestros',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
    bio: 'Experta en resolución de reclamaciones con enfoque en el cliente.',
  },
  {
    name: 'Diego Hernández',
    role: 'Director de Tecnología',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    bio: 'Lidera la transformación digital de nuestros servicios aseguradores.',
  },
]

export const VALUES = [
  {
    icon: '🛡️',
    title: 'Confianza',
    description: 'Construimos relaciones duraderas basadas en transparencia y compromiso con nuestros clientes.',
  },
  {
    icon: '⚡',
    title: 'Agilidad',
    description: 'Procesos rápidos y digitales para que obtengas tu póliza en minutos, no en días.',
  },
  {
    icon: '🤝',
    title: 'Cercanía',
    description: 'Un asesor personal que te acompaña en cada momento, desde la cotización hasta el siniestro.',
  },
  {
    icon: '🌟',
    title: 'Excelencia',
    description: 'Estándares de calidad superiores en cada producto y servicio que ofrecemos.',
  },
]
